### ISSUE TITLE
Symbol.Iterator

### ISSUE THREAD

**Issue by blake-regalia** [rdfjs/dataset-spec#13]
If the intention is align with `Set`, perhaps it would make more sense to define `[Symbol.iterator]()` as a method rather than `.iterator()`?

**Comment by bergos** [comment]
You are right. That's also what I tried to do, but didn't work for me with the respec script. Just tried a little bit. Will investigate a little bit more, but also PRs are very welcome :-)

**Comment by vhf** [comment]
I tried to get this to work with respec without success. It seems to be related to `maplike`…

**Comment by vhf** [comment]
I think I found what to do here: https://www.w3.org/TR/WebIDL-1/#idl-iterable because we cannot use a constant symbol value as attribute: https://heycam.github.io/webidl/#idl-symbol

**Comment by bergos** [comment]
fixed in 7b0e207a7a5e67931963b7ccc3d86c77f98ae227
