### ISSUE TITLE
.merge() => .union()

### ISSUE THREAD

**Issue by blake-regalia** [rdfjs/dataset-spec#16]
To keep inline with the semantics of the fundamental laws of [set algebra](https://en.wikipedia.org/wiki/Algebra_of_sets) we should prefer to use the method names `union`, `intersection`, `equals` and `includes`.

**Comment by bergos** [comment]
I don't have a strong opinion about it. Both are OK for me. But also worth to mention, `includes` is actually `has`, as it's aligned [Set.prototype.has()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/has).

**Comment by vhf** [comment]
I like this proposal, I often had to check the docs because I couldn't remember if `d1.merge(d2)` merged its argument d2 into the dataset d1 or returned a new dataset made of the union of both.

**Comment by blake-regalia** [comment]
> But also worth to mention, `includes` is actually `has`

I'm all good with `has` as well, but I was actually referring to [subset](https://en.wikipedia.org/wiki/Subset)/containment, which can be trivially implemented as `a.intersection(b).equals(b)`. I suppose that should actually go in a proposal to add such a method but I wanted to discuss w/ everyone on chat before. Perhaps another name would be better than `includes` tho since I can see that causing some confusion with `Array#includes`. Maybe `contains`?
