### ISSUE TITLE
Methods of DatasetCore

### ISSUE THREAD

**Issue by bergos** [rdfjs/dataset-spec#18]
I think we could reduce the interface of `DatasetCore` even a little bit more:

- `equals` can be built on top of the iterator.
- `reduce` can be also implement with the iterator.
- `toArray` can be implemented with the iterator, maybe we skip it completely.

**Comment by rubensworks** [comment]
> equals requires implementing isomorphic Dataset comparison, which is complex and can be built on top of the iterator.

Should `equals` test for isomorphism? One could argue that it makes sense to have this test for strict equality, and not trying to match up non-equal blank nodes. This would be consistent with the `has`/`contains` method.

`Dataset` could then have a separate `equalsIsomorphic` method.

**Comment by bergos** [comment]
I'm not sure if we should support different levels of `equals`. The use cases I have in mind would always need the isomorphic version. My typical use cases are:

- compare in automated test
- compare data from two different sources

Maybe the strict equals could be used if some code adds conditionally some quads and the initial Dataset and the result should be checked against each other. But there I would rather use `result.difference(initial).size === 0` or even use a flag.

I mainly fear that we open a trap. So I would like to see some use cases before we add a second `equals` method.

Maybe also a topic for another issue. I would like to make fast progress on the `DatasetCore`, so we could freeze that part of the spec and people can start using it already.

**Comment by rubensworks** [comment]
Tracking the issue of `equals` in #23.

**Comment by bergos** [comment]
I've updated the comment about `equals`. @rubensworks @vhf please give a 👍 then I make a PR and will push a reference implementation.

**Comment by bergos** [comment]
fixed in 94df2922616d15fbc4e92f656331fdbf920a841d
