### ISSUE TITLE
Freeze the DatasetCore part of the spec

### ISSUE THREAD

**Issue by bergos** [rdfjs/dataset-spec#32]
I would like to freeze the `DatasetCore` part of the spec, so people can already start to use it. That doesn't mean I want to delay the release of the rest of the spec like the representation spec, but I expect we will need some more iterations on the methods of the `Dataset` interface. If you agree in general, please leave a :+1:. 

- Where do we communicate the release candidate and ask for feedback? gitter? mailinglist?
- How do we make the freeze/release? We could make a 1.0.0 version and declare the non-Core stuff experimental/incomplete.
- What needs to be done before the release?
  - [x] #6
  - [x] #30
  - [x] #31
  - [x] #33

@vhf @rubensworks @blake-regalia

**Comment by rubensworks** [comment]
> Where do we communicate the release candidate and ask for feedback? gitter? mailinglist?

I think the RDFJS mailinglist and gitter would indeed be sufficient for now. I would wait for a bigger announcement on the semweb mailinglist(s) until `Dataset` has been finalized as well.

> How do we make the freeze/release? We could make a 1.0.0 version and declare the non-Core stuff experimental/incomplete.

Sounds good!

> What needs to be done before the release?

I went through the `DatasetCore` part again, and I think only #33 should also be resolved first.

**Comment by bergos** [comment]
Now that we have all issues solved, what do you think is a good time frame for people to review the spec before making the 1.0.0 release? Two weeks?

@rubensworks @blake-regalia @vhf

**Comment by vhf** [comment]
I suggest 2 weeks from the request for comments

**Comment by bergos** [comment]
I sent out the [mail](https://lists.w3.org/Archives/Public/public-rdfjs/2019Mar/0001.html) yesterday and also posted a link to the mail in the RDF/JS Gitter channel.
