### ISSUE TITLE
Add link to RDFJS spec

### ISSUE THREAD

**Issue by rubensworks** [rdfjs/dataset-spec#33]
As far as I can see, there is no link yet to the RDFJS spec (https://rdf.js.org/). We should add this in order to explain what a `Quad` is in the context of datasets.

**Comment by bergos** [comment]
fixed in fe19a312452faebbcd75942c952c79d78cd5ced5

**Comment by elf-pavlik** [comment]
Those links will change as we rename the repo and create index for multiple specs on rdf.js.org
