### ISSUE TITLE
Optional methods

### ISSUE THREAD

**Issue by rubensworks** [rdfjs/dataset-spec#4]
It makes sense for implementors of `Dataset` to not support all methods/fields.
As such, we may allow some methods to be optional.
Here is my suggestion:

### Mandatory

* size
* add/addAll
* delete
* equals
* has
* match
* toArray
* iterator

### Optional

* deleteMatches
* difference
* every
* filter
* forEach
* import
* intersection
* map
* merge
* some
* toCanonical
* toStream
* toString

I'm also wondering if it would make sense to completely detach these optional methods from `Dataset`, and just make them external helper functions. This is because all(?) of these methods can be implemented based on the set of mandatory methods of `Dataset`, and they don't need to know anything about the internals of this `Dataset` implementation.

**Comment by bergos** [comment]
Let's group the optional methods, cause I think most pro/against arguments are for a group of methods. I also added `.addAll()` to the list, as it's also just a `.forEach()` from `.add()` away.

### Array-like
- every
- filter
- forEach
- map
- some

### String
- toCanonical
- toString

### Stream
- import
- toStream

### Set theory
- difference
- intersection

### Shortcuts
- addAll
- merge
- deleteMatches

**Comment by bergos** [comment]
I see the `Dataset` in the same category like `Array`, `Map` and `Set`. Everyone is using them, cause you expect them to be optimized. We should consider this, if the optional method implemented with the mandatory methods costs more than just the overhead of calling the mandatory methods.

If the Array-like methods are used via `.toArray()` there is always the overhead of creating the Array. For methods like `.some()` the full Array may not even be required.

We could not agree on the String methods in the Representation spec, so maybe it's the best to also make them optional/custom for the Dataset spec.

Set theory methods are good candidates for a util library. It's OK for me if we make them optional/custom.

The Shortcuts methods are more about usability. The rdf-ext Dataset has them already and `.addAll()` is used quite often. Next in the list comes `.deleteMatches`. An alternative could be `.deleteAll()`, which would fit to the `.addAll()` method. `.merge()` is used rarely and is not that difficult to replace with a factory call + `.addAll()`.

**Comment by rubensworks** [comment]
Ok, so in summary, the string and set methods would not be mandatory. Makes sense to me.

Shall I open a PR to remove those from the spec? Or would you prefer to have them mentioned as optional @bergos?

**Comment by ktk** [comment]
I would prefer to leave them in as optional, otherwise we create yet another document/spec for them.

**Comment by bergos** [comment]
The Stream methods link the Dataset spec to the Representation spec. That's why I would like to make them mandatory.

**Comment by timbl** [comment]
Why do you think that it is Ok for implementations to not all implement all the routines?
The value of a spec is in interop.   The best way of getting that is for everyone to implement everything.  Then any program will work with any library.     Or you can define two levels, and give names to all over them.  But for example convenience functions which are very simple to implement should be mandatory.  In this case If they can easily be implemented in terms of the others, that doesn't mean tha they shouldn't be mandatory so as to have just one spec.

**Comment by rubensworks** [comment]
> Or you can define two levels

Agreed, this would indeed be better than having optional methods in the interface.

So next to the `Dataset` spec, it might makes sense to have a separate spec for util functions for string and set methods, as [suggested by](https://github.com/rdfjs/dataset-spec/issues/4#issuecomment-442650982) @bergos.

**Comment by bergos** [comment]
I create PR #11 to create a separate interface for mandatory and optional methods. Please check it and leave a comment.

**Comment by bergos** [comment]
By splitting up the `Dataset` into `DatasetCore` and `Dataset`, this issue should be resolved. @rubensworks please close if it's ok.

**Comment by rubensworks** [comment]
Yep, the new `DatasetCore` looks like a good solution for this!
