### ISSUE TITLE
Move current dataset implementation to spec and replace dataset with an optimized implementation

### ISSUE THREAD

**Issue by bergos** [rdfjs/dataset-spec#52]
The current [dataset implementation](https://github.com/rdfjs/dataset) was already very useful to find gaps in the spec and code + spec makes the standard more understandable. On the other side, having the simple and not optimized implementation as the reference could lead people to a package that may cause some bad experience from performance perspective.

That's why I would propose to move the current implementation to the spec repository and replace it with an indexed implementation based on @RubenVerborgh s [N3Store](https://github.com/rdfjs/N3.js). I started already working on it, based on [fork for RDF-Ext](https://github.com/rdf-ext/rdf-dataset-indexed) done by @vhf. You can find the current state [here](https://github.com/bergos/dataset-impl).

In this issue I would like to vote and get feedback if we can agree on moving the current implementation to the spec repository. Leave a :+1:  or :-1: to vote on the general idea. Please also leave feedback if we can copy the files and folders 1:1 or the code should be restructured. If there are more detailed comments or questions about the index implementation, we can open an issue in the code repository.

Or :eyes: for moving the reference implementation to `dataset-*` and the default implementation to `dataset`.

**Comment by RubenVerborgh** [comment]
It all depends on what the purpose of this repository is. Is it a reference implementation, or some optimal implementation?

The risk of having some level of optimality in these repos, is that they will/need to become "_the_ repo", which might be counter to our actual goals.

So the real vote here is probably not about dataset, but rather about the overarching goal. Right?

**Comment by ktk** [comment]
Not sure if I get Rubens comment, my POV is:

- `rdfjs/dataset` should be *the* version people use when they get in contact with RDFJS and need a good implementation. This is currently clearly not the case as it's the most simple implementation from code POV but not at all a fast one
- the work Thomas did based on Rubens code refactored by Victor should become that new, performant implementation

**Comment by timbl** [comment]
I agree with Ruben that there should not be only one reference implementation which becomes more important than the spec. Good practice is two have minimum of two implications anyway.  One simple and one fast sounds good.  Keep both?

**Comment by ktk** [comment]
We can surely keep both but I would clearly state in the GitHub repository name that it is a reference implementation and not a fast one. For example `dataset-primitive` or alike. And `dataset` would be the one people would/should pick by default.

**Comment by bergos** [comment]
Not sure, but maybe move was the wrong word. I propose to merge the current content of the [dataset](https://github.com/rdfjs/dataset) repository into the spec repository. Let's call that implementation the reference implementation.

Goal of the reference implementation:

- as simple as possible
- should support developers who like to write their own implementation
- should support the spec discussion
- less important than the spec

Goal of this repository:

- contains the dataset spec
- contains code and tools to support developers who like to write their own implementation

In the future the [dataset](https://github.com/rdfjs/dataset) should contain an optimized implementation for everyday usage. Maybe we can call it the default implementation.

Goal of the default implementation:

- fast, optimized code
- default for packages of the rdfjs organization
- good choice for everyday usage

That means we keep both implementations, but try to prevent that people have a bad experience by using a slow implementation.

**Comment by RubenVerborgh** [comment]
I think we should distinguish RDF/JS (the interfaces) versus specific implementations.

So perhaps give the default implementation a name and put it there?
And, on that note, is rdf-ext the right place?

**Comment by vhf** [comment]
I don't see the point in keeping this: https://github.com/rdfjs/dataset/blob/56fb402b4fe34c5551bcdef0145315802abe7764/DatasetCore.js  .

Removing it from `rdfjs/dataset` is important IMO, otherwise rdfjs newcomers could start using it thinking it is what rdfjs recommends. If they have a bad experience with it, the risk is that they think that rdfjs as a whole is not viable solution.

If it ends up being moved to the dataset-spec, it would be good to preface it with a disclaimer saying it shouldn't be used for serious projects and linking to better implementations. If it was up to me I wouldn't move it though, I would replace rdfjs/dataset with a better implementation and that's it.

**Comment by bergos** [comment]
@RubenVerborgh I agree if an implementation contains very specific optimizations and features that are not part of the spec, it should not be in the rdfjs organization. But the index is a very generic feature and doesn't add new features that are not part of the spec. Also rdfjs contains now already a lot of packages people will directly use, so I expect they will also start searching for packages in this organization.

rdf-ext contains some features, we could not agree in the spec (e.g. `toString()` methods in the data model), but I hope long term we can reduce the difference to a minimum or even zero and we can give up rdf-ext in favor of rdfjs.

More in detail: My plan was to extend the rdf-ext dataset from the new indexed rdfjs dataset and add the rdf-ext specific methods to it. Depending on the outcome of the [Dataset interface](https://rdf.js.org/dataset-spec/#dataset-interface) discussions, a new major version would still add new methods or maybe/hopefully is not required at all.

**Comment by RubenVerborgh** [comment]
@vhf 
> rdfjs newcomers could start using it thinking it is what rdfjs recommends

In any case, we need to clarify that RDF/JS is an _interface_ that _other_ libraries conform to.
I'm not sure when RDF/JS became a library itself.

@bergos
> rdf-ext contains some features, we could not agree in the spec (e.g. `toString()` methods in the data model),

As long as they are extensions, that should not be a problem, right?
Only when they are incompatible, there would be a problem.

**Comment by elf-pavlik** [comment]
I would prefer to keep any spec in dedicated repo from any implementation of the spec. If you see need to maintain two different implementation in @rdfjs organization, I would just have two separate repos for them, how they map to npm namespace sounds like separate issue to me.

**Comment by bergos** [comment]
@RubenVerborgh We have already lot of packages in the rdfjs organization and some will require a `DatasetCore` implementation. The one in the dependencies will look like a recommendation.

Theoretical it's not a problem that RDF-Ext adds features, but for example the `.toCanonical()` method of the dataset requires `jsonld.js`and that causes a few hundred extra KB in a webpack bundle. That caused already some discussions in the past, which I would like to avoid.

@elf-pavlik Two separate repos are OK for me. I would use `dataset-*` for the reference implementation and just `dataset` for the default, which would lead people to the right repo, I expect. This would also allow us to use a 1:1 mapping in npm. Otherwise it could be confusing.

**Comment by elf-pavlik** [comment]
> Two separate repos are OK for me. I would use dataset-* for the reference implementation and just dataset for the default, which would lead people to the right repo, I expect. This would also allow us to use a 1:1 mapping in npm. Otherwise it could be confusing.

👍 

> Theoretical it's not a problem that RDF-Ext adds features, but for example the .toCanonical() method of the dataset requires jsonld.jsand that causes a few hundred extra KB in a webpack bundle.

Doesn't it just require https://github.com/digitalbazaar/rdf-canonize ?

**Comment by blake-regalia** [comment]
I'm generally against RDFJS org publishing/hosting implementations at all. I think @RubenVerborgh N3.js should have stayed separate. It discourages devs from creating new implementations and creates the impression that the RDFJS impl is _the_ one to use so newcomers will likely not explore the alternatives.

**Comment by RubenVerborgh** [comment]
@blake-regalia We could still revert that.

**Comment by ktk** [comment]
We spent a ton of time moving stuff here so I really don't like the idea of reverting all of that

**Comment by bergos** [comment]
I'm a little bit tired of these discussions. I thought we agreed on having a RDF.js library. You can find that on the [mailing list](https://lists.w3.org/Archives/Public/public-rdfjs/2018Apr/0000.html).

If we can't agree on that, I will move all packages started by myself to a new organization, just for RDF/JS compatible packages without extra features, and handle it just like RDF-Ext where I make the main decisions.

@blake-regalia I thought of the rdfjs organization not only as an organization for specs but also as a community for JS developers around RDF. That includes mentioning alternative implementations in the docs and that's what we are doing even on the [first page of our website](http://rdf.js.org/).

**Comment by RubenVerborgh** [comment]
That's true @bergos. We shouldn't make things more difficult. In any case, no objections from my side.

However, I see an implicit point in @blake-regalia's comment. I gladly “donated” N3.js to rdfjs, that's fine with me. However, I wonder if, by doing so, we have not disadvantaged other current and future libraries, such as as Blake's graphy.js.

> That includes mentioning alternative implementations in the docs and that's what we are doing even on the [first page of our website](http://rdf.js.org/).

That is a very strong point though. I like it.

Added my :+1: above.

**Comment by elf-pavlik** [comment]
To clarify my vote on initial post
👎 to mixing specs and implementations in same repositories
👍 to keeping any RDFJS conformant library in @rdffs orga (if people maintaining it wish so), plus listing all conformant libraries in https://rdf.js.org no matter where they stay hosted (projects don't even have to use github at all for their canonical repository, or even publish to npm)

**Comment by bergos** [comment]
I added :eyes: as third option. Please make or update your vote.

**Comment by bergos** [comment]
I will continue in the `rdfjs-base` organization, so there is no need anymore to discuss how it could be integrated.

**Comment by vhf** [comment]
@RubenVerborgh 
> 
> > rdfjs newcomers could start using it thinking it is what rdfjs recommends
> 
> In any case, we need to clarify that RDF/JS is an _interface_ that _other_ libraries conform to.
> I'm not sure when RDF/JS became a library itself.

I agree. My worry is that people, upon finding the [@rdfjs/dataset](https://www.npmjs.com/package/@rdfjs/dataset) NPM package, wrongly assume that it's something the rdfjs community recommends using. From my point of view it is actually the opposite: it shouldn't be used in any software project. It is code meant to be read, not run.

The time limit to unpublish it from NPM being >100 days past I only see two options, either
* replace it with something people could depend on it their software projects
* [deprecate](https://docs.npmjs.com/cli/deprecate) all versions of it and add an explanation to its README.md

**Comment by bergos** [comment]
Should be solved by releasing the indexed implementation as a new minor version.

**Comment by ktk** [comment]
Just to clarify: Thomas will move the packages from Github `rdfjs` org to `rdfjs-base`, there is no change on NPM. The org on NPM will remain `@rdfjs` and we will publish there. So `@rdfjs/dataset` will become the indexed version.
