### ISSUE TITLE
Integrate performance test into this repository

### ISSUE THREAD

**Issue by bergos** [rdfjs/dataset-spec#53]
As part of the work for #52 I changed the code of @RubenVerborgh s [N3Store performance tests](https://github.com/rdfjs/N3.js/tree/master/perf) to work with any RDF/JS compatible data factory and dataset implementation which can be found [here](https://github.com/bergos/dataset-impl/tree/master/perf). I also made some changes that should simplify the integration of other tests, if there is a need for it. I think it would be useful to add the performance test tool to the dataset-spec repository, so developer which would like write a dataset implementation find all useful tools at one place. Please vote :+1: or :-1: and leave some feedback how it should be added to the repository. I was thinking of adding a `bin` folder for the CLI code and keep the rest or `perf` folder or just rename the `perf` folder.

**Comment by RubenVerborgh** [comment]
Good stuff, I like it. Would then drop it from `n3` when it's ready.

**Comment by bergos** [comment]
I will continue in the rdfjs-base organization, so there is no need anymore to discuss how it could be integrated.

**Comment by RubenVerborgh** [comment]
Thanks @bergos!
