### ISSUE TITLE
WebIDL `sequence` as function/method paramater

### ISSUE THREAD

**Issue by vhf** [rdfjs/dataset-spec#6]
Regarding the use of WebIDL `sequence` as expected parameter type for instance here: https://rdf.js.org/dataset-spec/dataset-spec.html#datasetfactory-interface , I think we should either indicate that implementing this spec by mutating the sequence won't be valid or find an alternative to `sequence`?

Otherwise although everything is passed by value, it seems dangerously easy to me to violate this spec:

```js
class Dataset {
  // …
  addAll (input) {
    if (input instanceof Dataset) {
      // …
    } else {
      let quad
      while (quad = input.pop()) {
        this.add(quad)
      }
    }
  }
}
```

**Comment by bergos** [comment]
Also the factory methods accept a sequence of quads and mutating should not be allowed. I think there is no way to describe it in WebID, so we only add a note to the methods?
