### ISSUE TITLE
Add .reduce (or replace .map and .filter with .reduce)

### ISSUE THREAD

**Issue by vhf** [rdfjs/dataset-spec#8]
To me `map` and `filter` are specialized versions of `reduce`, implementing them using `reduce` is easy while the opposite is not.

We can implement most of the things using `reduce` which is what makes me think it is the most important primitive. Other examples than `map` and `filter` would be `merge`, `forEach`, `all`, `any`, `every`, `flatMap`, `concat`, `groupBy`, `count`, `drop`, …

Having `Dataset.prototype.reduce` seems more useful than having `.map` and `.filter` but not `.reduce`.

I have seen Dataset `map` and `filter` chained in the wild, things like e.g. `someDataset.filter(…).map(…).toArray()` which is much less efficient than `someDataset.reduce(…)` while providing the exact same functionality. Having a `reduce` method might also help avoiding this kind of things.

To keep #4 in mind, I'd suggest making `reduce` mandatory and `map`, `filter` optional.

**Comment by bergos** [comment]
I added `.reduce` as the only method mandatory for the minimal dataset interface in PR #11. Please check it and leave a comment.

**Comment by bergos** [comment]
`.reduce()` was added in 7ba62f062eba66ffdfbf90addfecacad86ed2aed
